### PR TITLE
Add support to publish cfr as a binary using PyInstaller

### PR DESCRIPTION
**Pull request by amotl**
## About
Use [PyInstaller](https://pyinstaller.org/) to build self-contained application bundles of the [CrateDB Cluster Flight Recorder (CFR)](https://cratedb-toolkit.readthedocs.io/cfr/).

- GH-160

## Preview
See section "Artifacts » Produced during runtime" on [GHA run #9826830191](https://github.com/crate-workbench/cratedb-toolkit/actions/runs/9826830191).

### CODE REVIEW

**Comment by amotl** [comment]
In a fresh Python virtualenv using Python 3.11, using the commands outlined below, I am observing an error, apparently when trying to bundle pandas.

### Usage
```
pip install --editable='.[cfr]' pyinstaller
pyinstaller cratedb_toolkit/cfr/cli.py --name cratedb-cfr
```

### Error
```python
SubprocessDiedError: Child process died calling _is_package() with args=('pandas._libs',) and kwargs={}. Its exit code was -11.
```

### Traceback
```python
7730 INFO: Loading module hook 'hook-pandas.py' from '/Users/amo/dev/crate/ecosystem/cratedb-retentions/.venv-installer/lib/python3.11/site-packages/PyInstaller/hooks'...
Traceback (most recent call last):
  File "/Users/amo/dev/crate/ecosystem/cratedb-retentions/.venv-installer/bin/pyinstaller", line 8, in <module>
    sys.exit(_console_script_run())
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amo/dev/crate/ecosystem/cratedb-retentions/.venv-installer/lib/python3.11/site-packages/PyInstaller/__main__.py", line 231, in _console_script_run
    run()
  File "/Users/amo/dev/crate/ecosystem/cratedb-retentions/.venv-installer/lib/python3.11/site-packages/PyInstaller/__main__.py", line 215, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/Users/amo/dev/crate/ecosystem/cratedb-retentions/.venv-installer/lib/python3.11/site-packages/PyInstaller/__main__.py", line 70, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/Users/amo/dev/crate/ecosystem/cratedb-retentions/.venv-installer/lib/python3.11/site-packages/PyInstaller/building/build_main.py", line 1216, in main
    build(specfile, distpath, workpath, clean_build)
  File "/Users/amo/dev/crate/ecosystem/cratedb-retentions/.venv-installer/lib/python3.11/site-packages/PyInstaller/building/build_main.py", line 1156, in build
    exec(code, spec_namespace)
  File "/Users/amo/dev/crate/ecosystem/cratedb-retentions/cratedb-cfr.spec", line 4, in <module>
    a = Analysis(
        ^^^^^^^^^
  File "/Users/amo/dev/crate/ecosystem/cratedb-retentions/.venv-installer/lib/python3.11/site-packages/PyInstaller/building/build_main.py", line 556, in __init__
    self.__postinit__()

[...]

  File "/Users/amo/dev/crate/ecosystem/cratedb-retentions/.venv-installer/lib/python3.11/site-packages/PyInstaller/compat.py", line 583, in importlib_load_source
    mod_loader.exec_module(mod)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/amo/dev/crate/ecosystem/cratedb-retentions/.venv-installer/lib/python3.11/site-packages/PyInstaller/hooks/hook-pandas.py", line 15, in <module>
    hiddenimports = collect_submodules('pandas._libs')
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amo/dev/crate/ecosystem/cratedb-retentions/.venv-installer/lib/python3.11/site-packages/PyInstaller/utils/hooks/__init__.py", line 604, in collect_submodules
    if not is_package(package):
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/amo/dev/crate/ecosystem/cratedb-retentions/.venv-installer/lib/python3.11/site-packages/PyInstaller/utils/hooks/__init__.py", line 484, in is_package
    return isolated.call(_is_package, module_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amo/dev/crate/ecosystem/cratedb-retentions/.venv-installer/lib/python3.11/site-packages/PyInstaller/isolated/_parent.py", line 389, in call
    return isolated.call(function, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amo/dev/crate/ecosystem/cratedb-retentions/.venv-installer/lib/python3.11/site-packages/PyInstaller/isolated/_parent.py", line 307, in call
    raise SubprocessDiedError(
PyInstaller.isolated._parent.SubprocessDiedError: Child process died calling _is_package() with args=('pandas._libs',) and kwargs={}. Its exit code was -11.
```

**Comment by amotl** [comment]
That other issue describes the same problem.

- https://github.com/pyinstaller/pyinstaller/issues/8430

Indeed, coming from the suggestion at https://github.com/pyinstaller/pyinstaller/issues/8430#issuecomment-2079002534, the reason is apparently that pandas is broken within the virtualenv at hand.

```python
>>> import pandas._libs
Segmentation fault: 11
```

**Comment by amotl** [comment]
Hi again. I've added a basic CI/GHA workflow definition with 7fb9df3bb0, and reported [about the outcome](https://github.com/crate-workbench/cratedb-toolkit/issues/160#issuecomment-2212415869) on the tracking ticket.

Building upon this, we can think about other build- and publishing-destinations/-procedures/-cycles on behalf of subsequent iterations, if you agree with that approach, @seut.

**Comment by amotl** [comment]
- Draft for high-level documentation is ready at https://cratedb-guide--55.org.readthedocs.build/admin/troubleshooting/cfr.html.
- PR at https://github.com/crate/cratedb-guide/pull/55.

**Review by seut — APPROVED** [review]
👍 thank you!

**Pull request merged**
